version: 2.1
jobs:
  build:
    #No. of servers/machines
    parallelism: 1

    docker:
      - image: circleci/ruby:3.0.0-node-browsers

    #application directory change it with your application directory name
    working_directory: ~/polly
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      RAILS_ENV: "test"
      RACK_ENV: "test"

    steps:
      - checkout
      - run: gem install bundler:2.2.3

      #install sqlite dependency

      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev

      # Bundle install

      - run: bundle config set --local path 'vendor/bundle'
      - run: bundle install --path vendor/bundle

      # Setup database

      - run: cp config/database.yml.ci config/database.yml
      - run: bundle exec rake db:create db:schema:load --trace

      # Yarn install

      - run: bin/yarn install --cache-folder vendor/node_modules

      # Generate assets

      - run: bin/webpack
      - run: bundle exec rails webpacker:compile

      # store test

      - store_test_results:
          path: test-results

      # Unit tests

      - run:
          shell: /bin/bash
          command: bundle exec rake test --trace
workflows:
  version: 2
  commit:
    jobs:
      - build
